# Tensors

Imports

In [1]:
import torch as tr
import numpy as np

In [2]:
data = [[1,2],[3,4]]
x_data = tr.tensor(data)

In [3]:
np_arr = np.array(data)
x_np = tr.from_numpy(np_arr)

In [4]:
x_ones = tr.ones_like(x_data)
print(f"Ones Tensor : \n{x_ones}")

Ones Tensor : 
tensor([[1, 1],
        [1, 1]])


In [5]:
x_rand = tr.rand_like(x_data, dtype = tr.float)
print(f"Random Tensor : \n {x_rand}")

Random Tensor : 
 tensor([[0.9780, 0.7122],
        [0.1323, 0.7049]])


In [6]:
shape = (2,3,)

rand_tensor = tr.rand(shape)
ones_tensor = tr.ones(shape)
zeros_tensor = tr.zeros(shape)

print(f"Random Tensor : \n {rand_tensor}")
print(f"ones Tensor : \n {ones_tensor}")
print(f"Zeros Tensor : \n {zeros_tensor}")

Random Tensor : 
 tensor([[0.0364, 0.6026, 0.8412],
        [0.6325, 0.0698, 0.2192]])
ones Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
tensor = tr.rand(3,4)

print(tensor)

tensor([[0.5837, 0.2293, 0.6139, 0.7718],
        [0.0839, 0.7181, 0.6664, 0.0499],
        [0.2668, 0.8431, 0.9955, 0.4394]])


In [8]:
print(f"Shape of tensor: {tensor.shape}")

print(f"Datatype of tensor : {tensor.dtype}")
      
print((f"Device of the tensor : {tensor.device}"))

Shape of tensor: torch.Size([3, 4])
Datatype of tensor : torch.float32
Device of the tensor : cpu


In [9]:
tensor = tr.ones(3,4)

print(f"First row : {tensor[0,:]}")
print(f"First column : {tensor[:,0]}")
print(f"Last Column : {tensor[:,-1]}")

tensor[:,1] = 0
print(tensor)

First row : tensor([1., 1., 1., 1.])
First column : tensor([1., 1., 1.])
Last Column : tensor([1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [10]:
t1 = tr.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [11]:
y1 = tensor @ tensor.T
print(y1)

y2 = tensor.matmul(tensor.T)
print(y2)

y3 = tr.zeros_like(y1)

print(y3)

tr.matmul(tensor, tensor.T, out = y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = tr.zeros_like(z1)
tr.mul(tensor, tensor, out = z3)

print(z1, z2, z3)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [12]:
agg = tensor.sum()

print(agg)

agg_item = agg.item()

print(agg_item)

print(type(agg_item))

tensor(9.)
9.0
<class 'float'>


In [13]:
print(tensor,"\n")

tensor.add_(5)

print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [14]:
t = tr.ones(5)
print(f"t : {t}")

n = t.numpy()

print(f"n : {n}")

t : tensor([1., 1., 1., 1., 1.])
n : [1. 1. 1. 1. 1.]


In [15]:
t.add_(2)
print(t,"\n")
print(n,"\n")

tensor([3., 3., 3., 3., 3.]) 

[3. 3. 3. 3. 3.] 



In [16]:
n = np.ones(5)

t = tr.from_numpy(n)

print(f"n : {n}")
print(f"t : {t}")

n : [1. 1. 1. 1. 1.]
t : tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [17]:
np.add(n, 1, out = n)

print(f"n : {n}")
print(f"t : {t}")

n : [2. 2. 2. 2. 2.]
t : tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
