# AutoGrad

imports

In [1]:
import torch as tr

In [2]:
x = tr.ones(5)
y = tr.zeros(3)
w = tr.randn(5,3, requires_grad = True)
#print(w)
print(w.mean(), w.var())
b = tr.randn(3,requires_grad = True)
z = tr.matmul(x,w)+b
loss = tr.nn.functional.binary_cross_entropy_with_logits(z,y)

tensor(-0.1033, grad_fn=<MeanBackward0>) tensor(1.1535, grad_fn=<VarBackward0>)


In [3]:
print(f"Gradient fun for z manual init : {z.grad_fn}")
print(f"Gradient fun for loss manual init : {loss.grad_fn}")

Gradient fun for z manual init : <AddBackward0 object at 0x78255b9d3580>
Gradient fun for loss manual init : <BinaryCrossEntropyWithLogitsBackward0 object at 0x78255b9d24d0>


In [4]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0149, 0.0166, 0.2638],
        [0.0149, 0.0166, 0.2638],
        [0.0149, 0.0166, 0.2638],
        [0.0149, 0.0166, 0.2638],
        [0.0149, 0.0166, 0.2638]])
tensor([0.0149, 0.0166, 0.2638])


In [5]:
z = tr.matmul(x, w)+b
print(z.requires_grad)

with tr.no_grad():
    z = tr.matmul(x,w)+b
    
print(z.requires_grad)

True
False


In [6]:
z = tr.matmul(x,w)+b
z_det = z.detach()
print(z_det.requires_grad)

False


In [7]:
inp = tr.eye(4,5, requires_grad = True)
out = (inp+1).pow(2).t()
out.backward(tr.ones_like(out), retain_graph = True)# same dimension as mat out
print(f"First call : \n{inp.grad}")
out.backward(tr.ones_like(out), retain_graph = True)
print(f"Second call : \n{inp.grad}")
inp.grad.zero_()
out.backward(tr.ones_like(out), retain_graph = True)
print(f"\n Call after zeroing gradient \n{inp.grad}")

First call : 
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
Second call : 
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])

 Call after zeroing gradient 
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
